# Generated by Django 3.1.2 on 2020-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='avatar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
